/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package oc.msm.amq;

import org.apache.activemq.ActiveMQConnection;
import org.apache.activemq.ActiveMQConnectionFactory;

import javax.jms.*;
import java.lang.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class App {
	private static Logger LOGGER = LoggerFactory.getLogger(App.class);

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

		var user = ActiveMQConnection.DEFAULT_USER;
		var password = ActiveMQConnection.DEFAULT_PASSWORD;

		ActiveMQConnectionFactory connectionFactory = new ActiveMQConnectionFactory("tcp://mq:61616");
		Connection connection = null;

		try {
			LOGGER.info("connecting ...");
			connection = connectionFactory.createConnection();
			connection.start();

			Session session = connection.createSession(false, Session.AUTO_ACKNOWLEDGE);
			Destination destination = session.createQueue("bpasreceiveQueue");

			MessageProducer producer = session.createProducer(destination);
			producer.setDeliveryMode(DeliveryMode.NON_PERSISTENT);

			LOGGER.info("create message ...");
			String text = "First Test Message";
			TextMessage message = session.createTextMessage();
			message.setStringProperty("JMSType",
					"com.adcubum.syrius.corporg.bpm.bpas.bl.api.notification.v1.BusinessProcessFinishedEventNotification");

			LOGGER.info("sending message ...");
			message.setText(text);
			producer.send(message);

		} catch (JMSException e) {
			LOGGER.error("ERROR: {}", e.getMessage());
			e.printStackTrace();
		} finally {
			try {
				LOGGER.info("closing connection ...");
				connection.close();
			} catch (JMSException e) {
				LOGGER.error("Error closing connection: {}", e.getMessage());
			}
		}

    }
}
